#!/bin/bash

DOTFILES_DIR="$HOME/repos/github.com/Soeky/dotfiles"
XDG_CONFIG_HOME="$HOME/.config"
REPOS="$HOME/repos"
GHREPOS="$REPOS/github.com/Soeky"
SCRIPTS="$DOTFILES_DIR/scripts"

create_directories() {
  local directories=("$@")
  for dir in "${directories[@]}"; do
    mkdir -p "$dir"
  done
}

create_symlinks() {
  local items=("$@")
  for item in "${items[@]}"; do
    IFS=':' read -r source target <<<"$item"
    if [ -L "$target" ]; then
      echo "Removing existing symlink $target"
      unlink "$target"
    elif [ -d "$target" ]; then
      echo "Warning: $target is a directory. Skipping..."
      continue
    elif [ -e "$target" ]; then
      echo "Warning: $target already exists. Skipping..."
      continue
    fi
    ln -s "$DOTFILES_DIR/$source" "$target"
    echo "Created symlink for $source"
  done
}


common_items=(
  ".tmux.conf:$HOME/.tmux.conf"
  "nvim:$XDG_CONFIG_HOME/nvim"
  ".bashrc:$HOME/.bashrc"
  ".bash_profile:$HOME/.bash_profile"
)




create_directories "$DOTFILES_DIR" "$HOME/.local/bin" "$REPOS" "$GHREPOS" "$SCRIPTS"
create_symlinks "${common_items[@]}"

ln -sf "$PWD/bash/.bash_profile" "$HOME"/.bash_profile
ln -sf "$PWD/bash/.bashrc" "$HOME"/.bashrc
ln -sf "$PWD/i3/" "$XDG_CONFIG_HOME"
ln -sf "$PWD/i3blocks/" "$XDG_CONFIG_HOME"

