#!/bin/bash

cpu_usage=$(grep 'cpu ' /proc/stat | awk -v RS="" '{usage=($2+$4)*100/($2+$4+$5)} END {print usage}')
printf "CPU: %.1f%%\n" "$cpu_usage"

if [ "$(echo "$cpu_usage > 90" | bc -l)" -eq 1 ]; then
    echo "#FF0000"
elif [ "$(echo "$cpu_usage > 80" | bc -l)" -eq 1 ]; then
    echo "#FFAE00"
elif [ "$(echo "$cpu_usage > 70" | bc -l)" -eq 1 ]; then
    echo "#FFF600"
fi
