#!/bin/bash

xrandr --dpi 192 \
    --output eDP-1 --mode 3840x2400 --scale 1x1 --pos 0x0 --rate 60 \
    --output DP-3-1 --mode 2560x1440 --scale 2x2 --pos 3840x0 --rate 144 \
    --output DP-3-3-1 --mode 2560x1440 --scale 2x2 --pos 6400x0 --rate 165
